## Importing Necessary Libaries

In [2]:
# Data Manipulation packages
import pandas as pd
import numpy as np

# Data Visualization packages
import seaborn as sns
import matplotlib.pyplot as plt

# sql
from sqlalchemy import create_engine

In [3]:
engine = create_engine("mysql+pymysql://root:246824@localhost:3306/Olist_db")

In [4]:
query = """
SELECT * 
FROM rfm_data;
"""

In [5]:
rfm_df = pd.read_sql(query,engine)
rfm_df.head(5)

                 customer_unique_id  recency  frequency  monetary
0  0000366f3b9a7992bf8c76cfdf3221e2      111          1    141.90
1  0000b849f77a49e4a4ce2b2a4ca5be3f      114          1     27.19
2  0000f46a3911fa3c0805444483337064      537          1     86.22
3  0000f6ccb0745a6a4b88665a16c9f078      321          1     43.62
4  0004aac84e0df4da2b147fca70cf8255      288          1    196.89

In [6]:
rfm_df['recency'].sort_values(ascending=True)

4587       0
90464      0
66035      0
12423      0
46730      0
        ...
6221     695
51390    695
35804    695
17357    695
47873    713
Name: recency, Length: 93336, dtype: int64

In [7]:
rfm_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 93336 entries, 0 to 93335
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_unique_id  93336 non-null  str
 1   recency             93336 non-null  int64
 2   frequency           93336 non-null  int64
 3   monetary            93336 non-null  float64
dtypes: float64(1), int64(2), str(1)
memory usage: 2.8 MB

In [8]:
rfm_df.duplicated().sum()

np.int64(0)

There is no duplicated values.

In [9]:
# Quintile scoring (1-5)
def score_rfm(rfm_df):
    rfm_df['R_score'] = pd.qcut(rfm_df['recency'], 5, labels=[5,4,3,2,1]).astype(int)  # recency နည်းရင် score မြင့်
    rfm_df['F_score'] = pd.qcut(rfm_df['frequency'].rank(method='first'), 5, labels=[1,2,3,4,5]).astype(int)
    rfm_df['M_score'] = pd.qcut(rfm_df['monetary'], 5, labels=[1,2,3,4,5]).astype(int)

    # RFM score

    rfm_df["RFM_score"] = (
        rfm_df["R_score"].astype(str)
        + rfm_df["F_score"].astype(str)
        + rfm_df["M_score"].astype(str)
    )
    rfm_df["RFM_sum"] = rfm_df["R_score"] + rfm_df["F_score"] + rfm_df["M_score"]

    return rfm_df

In [10]:
def assign_segment(row):

    R = int(row['R_score'])
    F = int(row['F_score'])
    M = int(row['M_score'])

    # recent,frequent, big spender
    if R >= 4 and F >= 4 and M >= 4:
        return 'Champions'

    # Was valuable customer but not now (need to take action)
    if R <= 2 and F >= 3 and M >= 3:
        return 'At Risk - High Value'

    if R <= 2 and F <=2 and M <=2:
        return 'Lost'

    if R >= 4 and F <= 2:
        return 'New/Potential'

    if M >= 3:
        return 'Loyal - High value'
    return 'Loyal - Low value'

In [11]:
rfm_df = score_rfm(rfm_df)
rfm_df.head(5)

,customer_unique_id,recency,frequency,monetary,R_score,F_score,M_score,RFM_score,RFM_sum
0,0000366f3b9a7992bf8c76cfdf3221e2,111,1,141.90,4,1,4,414,9
1,0000b849f77a49e4a4ce2b2a4ca5be3f,114,1,27.19,4,1,1,411,6
2,0000f46a3911fa3c0805444483337064,537,1,86.22,1,1,2,112,4
3,0000f6ccb0745a6a4b88665a16c9f078,321,1,43.62,2,1,1,211,4
4,0004aac84e0df4da2b147fca70cf8255,288,1,196.89,2,1,4,214,7

In [12]:
rfm_df['segment'] = rfm_df.apply(assign_segment, axis=1)

In [13]:
rfm_df.head(5)

,customer_unique_id,recency,frequency,monetary,R_score,F_score,M_score,RFM_score,RFM_sum,segment
0,0000366f3b9a7992bf8c76cfdf3221e2,111,1,141.90,4,1,4,414,9,New/Potential
1,0000b849f77a49e4a4ce2b2a4ca5be3f,114,1,27.19,4,1,1,411,6,New/Potential
2,0000f46a3911fa3c0805444483337064,537,1,86.22,1,1,2,112,4,Lost
3,0000f6ccb0745a6a4b88665a16c9f078,321,1,43.62,2,1,1,211,4,Lost
4,0004aac84e0df4da2b147fca70cf8255,288,1,196.89,2,1,4,214,7,Loyal - High value

In [14]:
 summary = rfm_df.groupby("segment").agg(
        customers=("customer_unique_id", "count"),
        avg_recency=("recency", "mean"),
        avg_frequency=("frequency", "mean"),
        avg_monetary=("monetary", "mean"),
    ).sort_values("customers", ascending=False)

In [15]:
summary['customer_percentage'] = (summary['customers'] / summary['customers'].sum() * 100
).round(2)

summary

,customers,avg_recency,avg_frequency,avg_monetary,customer_percentage
segment,,,,,
Loyal - High value,27229,240.600389,1.028683,220.227218,29.17
Loyal - Low value,25169,238.578887,1.007430,54.974736,26.97
New/Potential,15033,90.723475,1.000000,163.565572,16.11
At Risk - High Value,13101,393.431723,1.074345,243.726699,14.04
Champions,6516,90.913904,1.180632,312.054359,6.98
Lost,6288,396.803117,1.000000,55.777554,6.74

In [16]:
print("=== RFM Table (sample) ===")
rfm_df.head(10)

=== RFM Table (sample) ===

,customer_unique_id,recency,frequency,monetary,R_score,F_score,M_score,RFM_score,RFM_sum,segment
0,0000366f3b9a7992bf8c76cfdf3221e2,111,1,141.90,4,1,4,414,9,New/Potential
1,0000b849f77a49e4a4ce2b2a4ca5be3f,114,1,27.19,4,1,1,411,6,New/Potential
2,0000f46a3911fa3c0805444483337064,537,1,86.22,1,1,2,112,4,Lost
3,0000f6ccb0745a6a4b88665a16c9f078,321,1,43.62,2,1,1,211,4,Lost
4,0004aac84e0df4da2b147fca70cf8255,288,1,196.89,2,1,4,214,7,Loyal - High value
5,0004bd2a26a76fe21f786e4fbd80607f,146,1,166.98,4,1,4,414,9,New/Potential
6,00050ab1314c0e55a6ca13cf7181fecf,131,1,35.38,4,1,1,411,6,New/Potential
7,00053a61a98854899e70ed204dd4bafe,182,1,419.18,3,1,5,315,9,Loyal - High value
8,0005e1862207bf6ccc02e4228effd9a0,543,1,150.12,1,1,4,114,6,Loyal - High value
9,0005ef4cd20d2893f0d9fbd94d3c0d97,170,1,129.76,4,1,3,413,8,New/Potential

In [17]:
print("\n=== Segment Summary ===")
summary

=== Segment Summary ===

,customers,avg_recency,avg_frequency,avg_monetary,customer_percentage
segment,,,,,
Loyal - High value,27229,240.600389,1.028683,220.227218,29.17
Loyal - Low value,25169,238.578887,1.007430,54.974736,26.97
New/Potential,15033,90.723475,1.000000,163.565572,16.11
At Risk - High Value,13101,393.431723,1.074345,243.726699,14.04
Champions,6516,90.913904,1.180632,312.054359,6.98
Lost,6288,396.803117,1.000000,55.777554,6.74

In [18]:
rfm_df.to_csv("rfm_output.csv", index=False)
print("\nSaved full RFM table to rfm_output.csv")

Saved full RFM table to rfm_output.csv

As we expected, Loyal customers base have the biggest customer base since Loyal is the catch-all "everyone else" bucket in the segment logic, so it's naturally going to be the biggest. This distribution actually looks reasonable and fairly typical for a real customer base.

## Two areas need to focus for the further analysis.
1.  Spliting the Loyal customer into 2 categories: Low expense Loyal customer and Big expense Loyal customer based on the Monetary.

2. Priotize "At risk: high value" customer to maintain the customer churns. Must to take action.

In [19]:
at_risk_df = rfm_df[rfm_df['segment']=='At Risk - High Value'].copy()
at_risk_df.head(5)

,customer_unique_id,recency,frequency,monetary,R_score,F_score,M_score,RFM_score,RFM_sum,segment
305,00cc12a6d8b578b8ebd21ea4e2ae8b27,526,2,126.20,1,5,3,153,9,At Risk - High Value
469,013f4353d26bb05dc6652f1269458d8d,274,2,356.39,2,5,5,255,12,At Risk - High Value
501,015557c9912277312b9073947804a7ba,485,2,315.12,1,5,5,155,11,At Risk - High Value
765,02168ea18740a0fdaaa15f11bebba5db,324,2,264.04,2,5,5,255,12,At Risk - High Value
894,027803eb28cc01fbdf5da72b109fabee,316,2,101.43,2,5,3,253,10,At Risk - High Value

In [20]:
at_risk_df.info()

<class 'pandas.DataFrame'>
Index: 13101 entries, 305 to 93333
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_unique_id  13101 non-null  str
 1   recency             13101 non-null  int64
 2   frequency           13101 non-null  int64
 3   monetary            13101 non-null  float64
 4   R_score             13101 non-null  int64
 5   F_score             13101 non-null  int64
 6   M_score             13101 non-null  int64
 7   RFM_score           13101 non-null  str
 8   RFM_sum             13101 non-null  int64
 9   segment             13101 non-null  str
dtypes: float64(1), int64(6), str(3)
memory usage: 1.1 MB

In [21]:
at_risk_df.head(10)

,customer_unique_id,recency,frequency,monetary,R_score,F_score,M_score,RFM_score,RFM_sum,segment
305,00cc12a6d8b578b8ebd21ea4e2ae8b27,526,2,126.20,1,5,3,153,9,At Risk - High Value
469,013f4353d26bb05dc6652f1269458d8d,274,2,356.39,2,5,5,255,12,At Risk - High Value
501,015557c9912277312b9073947804a7ba,485,2,315.12,1,5,5,155,11,At Risk - High Value
765,02168ea18740a0fdaaa15f11bebba5db,324,2,264.04,2,5,5,255,12,At Risk - High Value
894,027803eb28cc01fbdf5da72b109fabee,316,2,101.43,2,5,3,253,10,At Risk - High Value
1191,0333b2fc6ba7014702e08ef613850270,296,2,93.00,2,5,3,253,10,At Risk - High Value
1331,0396c443fdda5498c7e9ed5b34871c5a,481,2,120.84,1,5,3,153,9,At Risk - High Value
1411,03dabd77cb0ed7a26fafe19e36b67742,471,2,99.45,1,5,3,153,9,At Risk - High Value
1547,043aee247e71edff7045664609f4d806,408,2,405.41,1,5,5,155,11,At Risk - High Value
1573,0451ef5a31cea3e14ce02d768d7c9943,437,2,387.39,1,5,5,155,11,At Risk - High Value

In [ ]:
at_risk = at_risk_df.sort_values(
    by = ['monetary','frequency'], ascending = [False,False]
)

at_risk

,customer_unique_id,recency,frequency,monetary,R_score,F_score,M_score,RFM_score,RFM_sum,segment
79617,da122df9eeddfedc1dc1f5349a1a690c,515,2,7571.63,1,5,5,155,11,At Risk - High Value
80444,dc4802a71eae9be1dd28f5d788ceb526,563,1,6929.31,1,5,5,155,11,At Risk - High Value
93059,ff4159b92c40ebe40454e3e6a7c35ed6,462,1,6726.66,1,5,5,155,11,At Risk - High Value
87127,eebb5dda148d3893cdaf5b5ca3040ccb,498,1,4764.34,1,5,5,155,11,At Risk - High Value
86869,edf81e1f3070b9dac83ec83dacdbb9bc,498,1,4194.76,1,5,5,155,11,At Risk - High Value
...,...,...,...,...,...,...,...,...,...,...
6457,118be57d1b7de439453a0c6625ad7934,375,2,87.38,2,5,3,253,10,At Risk - High Value
65309,b2cdf76962cdd5c1c1534af71e82ebeb,296,1,87.38,2,4,3,243,9,At Risk - High Value
48177,83e75db9c4f88190e300f1a6cca95540,582,1,87.37,1,3,3,133,7,At Risk - High Value
81505,df25efeec134052aa0bca8b60e9e5592,290,1,87.37,2,5,3,253,10,At Risk - High Value
42670,74cb55ab807c4e4473ed0c7046ba9b58,337,1,87.36,2,3,3,233,8,At Risk - High Value

In [22]:
at_risk_df.to_csv("winback_at_risk_customers.csv", index = False)